spring:
  application:
    name: BT_25-11_SpringSecurityJWT_JWT
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/bt_25-11-2024_jwt}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      load-on-startup: 1
